config/routes.rb
Rails.application.routes.draw do
  devise_for :buyers
  devise_for :brokers
  devise_for :admins
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"
  get 'home/transactions'
  get 'portfolio/broker' => 'home#broker_portfolio', as: 'home_broker_portfolio'
  get 'portfolio/buyer' => 'home#buyer_portfolio', as: 'home_buyer_portfolio'
  get 'portfolio/broker/stocks' => 'home#broker_show_stocks', as: 'home_broker_show_stocks'
  get 'portfolio/buyer/stocks' => 'home#buyer_show_stocks', as: 'home_buyer_show_stocks'

  post 'stocks/search' => 'stocks#create', as: 'stocks_create'
  get 'stocks/show/:id' => 'stocks#show', as: 'stocks_show'
  get 'stocks/chart' => 'stocks#chart', as: 'stocks_chart'
  put 'stocks/broker/add/:id' => 'stocks#broker_add', as: 'stocks_broker_add'
  get 'stocks/buyer/new/:id' => 'stocks#buy', as: 'stocks_buy'
  post 'stocks/buyer/create/:id' => 'stocks#buyer_create', as: 'stocks_buyer_create'
  delete 'stocks/show/:id' => 'stocks#broker_delete', as: 'stocks_broker_delete'

  get 'admins/index'
  get 'admins/new/user'  => 'admins#new_user',   as: 'admins_new_user'
  post 'admins/new/user' => 'admins#create_user', as: 'admins_create_user'
  get 'admins/show/user/:id' => 'admins#show_user', as: 'admins_show_user'
  get 'admins/edit/user/:id' => 'admins#edit_user', as: 'admins_edit_user'
  put 'admins/edit/user/:id' => 'admins#update_user', as: 'admins_update_user'
  delete 'admins/edit/user/:id' => 'admins#cancel_user', as: 'admins_cancel_user'
  get 'admins/:id/approve'=> 'admins#approve_user', as: 'admins_approve_user'
  get 'admins/pending' => 'admins#pending', as: 'admins_pending'
end

app/views/admins/edit_user.html.erb
<div class="bg-white mt-5 mb-5 edit-card">
  <%= form_with method: :put, scope: :user, url: admins_edit_user_path, local:true do |f| %>

  <div class="row">
    <div class="col-md-3 border-right">
      <div class="mt-3 ms-3">
        <%= link_to admins_show_user_path, :class => "text-start back-arrow" do %>
          <i class="fas fa-arrow-left text-dark"></i>
        <% end %>
      </div>
       
      <div class="align-items-center text-center p-3">
        <% if @user.avatar.attached? %>
          <%= image_tag @user.avatar.variant(resize: "150x150!"), class:  "rounded-circle mt-3 mb-2" %>
        <% else %>
          <%= image_tag("default_profile.jpg", class: "rounded-circle mt-3 mb-2", height: '150', width: '150') %>
        <% end %>
        <div class="mt-2 mb-3 justify-content-center">
          <%= f.label :avatar, "Edit Image", class: "btn btn-sm btn-secondary btn-photo border-secondary text-dark disabled" %>
          <%= f.file_field :avatar, class: "input_file" %> </div>
          <span class="font-weight-bold"><%= @user.name %></span><br>
          <span class="text-black-50"><%= @user.email %></span>
          <span></span>
        </div>
      </div>
    <div class="col-md-5 border-right">
     
        <div class="form-inputs p-3 pt-4">
          <div class="mb-3 d-flex justify-content-center mt-5">
            <%= f.text_field :name,
                        required: true,
                        placeholder: 'Name',
                        class: 'form-control',
                        input_html: { autocomplete: "name" }%>
            </div>
            <div class="mb-3 d-flex justify-content-center">
              <%= f.text_field :email,
                          required: true,
                          placeholder: 'Email',
                          class: 'form-control',
                          input_html: { autocomplete: "email" }%>
            </div>
            <div class="form-actions mb-3 mt-3 d-flex justify-content-center p-1">
              <%= f.submit "Edit", :class => 'btn btn-action btn-md btn-warning' %>
            </div>
          </div> 
        </div>
        <div class="col-md-4 p-3 pt-4">
          <div class="mb-1 mt-5 d-flex justify-content-center">
            <h5>Cancel account</h5>
          </div>
          <div class="mb-3 d-flex justify-content-center">
            <%= link_to "Cancel my account", admins_cancel_user_path, data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-sm btn-danger" %></p>
          </div>
        </div>
    </div>
  </div>
  <% end %>
</div>

app/views/admins/index.html.erb
<div class="d-flex flex-column dashboard">
  <div class="mb-3">
    <%= link_to root_path, :class => "mt-3 text-start fs-4" do %>
      <i class="fas fa-arrow-left text-dark"></i>
    <% end %>
  </div>
  <h1>List of Users</h1>
  <div class="mt-4">
    <%= link_to admins_new_user_path, class: "btn btn-dark btn-sm me-2 rounded-pill add-user-btn fw-bold" do %>
      <span class="fas fa-plus me-2"></span> Add User
    <% end %>
  </div>
<div class="table-responsive">
  <table class="table table-hover mt-3">
  <thead class="table-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Type</th>
      <th scope="col">Email</th>
      <th scope="col">Status</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <% @users.each_with_index do |user, index| %>
  <tbody>
    <tr>
      <th scope="row"><%= index + 1 %></th>
      <td><%= user.name %></td>
      <td><%= user.type %></td>
      <td><%= user.email %></td>
      <td><span class="text-warning"><%= "Pending" unless user.approved == true%> </span></td>
      <td class="text-center">
        <%= link_to 'View User', admins_show_user_path(user.id), :class => "btn btn-action btn-sm btn-secondary text-white", :id => 'viewUserId' %>
      </td>
      <td class="text-center">
        <%= link_to 'Edit User', admins_edit_user_path(user.id), :class => "btn btn-action btn-sm btn-warning text-dark", :id => 'editUserId' %>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>
</div>
  
  </div>

app/views/admins/new_user.html.erb
<%= form_with method: :post, scope: :user, url: admins_new_user_path , local:true do |f| %>
<div class="bg-white mt-5 mb-5 edit-card">
  <div class="row">
    <div class="col-md-3 border-right">
      <div class="mt-3 ms-3">
        <%= link_to admins_index_path, :class => "text-start back-arrow" do %>
          <i class="fas fa-arrow-left text-dark"></i>
        <% end %>
      </div>
      <div class="d-flex flex-column align-items-center text-center p-3 py-5">
        <%= image_tag("default_profile.jpg", class: "rounded-circle mt-5 mb-2", height: '150', width: '150') %>
        <span></span>
      </div>
    </div>
    <div class="col-md-5 border-right">
      <div class="p-3 pt-4">
        <div class="mt-5 d-flex justify-content-center">
          <h5>User Information</h5>
        </div>
        <div class="mb-3 mt-3 form-floating">
          <%= f.text_field :name,
                        required: true,
                        placeholder: 'Enter your Name',
                        class: 'form-control new-form' %>
          <%= f.label :name %>
        </div>
        <div class="mb-3 mx-auto form-floating">
          <%= f.text_field :email,
                          required: true,
                          placeholder: 'Enter your Email',
                          class: 'form-control new-form' %>
          <%= f.label :email %>
        </div>
        <div class="mb-3 mx-auto form-floating">
          <%= f.password_field :password,
                          placeholder: 'Enter a Password',
                          class: 'form-control new-form' %>
          <%= f.label :password %>
        </div>
        <div class="mb-3 mx-auto form-floating">
          <%= f.password_field :password_confirmation, placeholder: 'Confirm Password', class: 'form-control new-form',
                          autocomplete: "new-password" %>
          <%= f.label :password_confirmation %>
        </div>
        <div class="form-actions mb-3 mt-3 d-flex justify-content-center p-1">
          <%= f.submit "Create", :class => 'btn btn-action btn-md btn-dark' %>
        </div>
      </div>
    </div>
    <div class="col-md-4 p-3 pt-4">
      <div class="mb-1 mt-5 d-flex justify-content-center">
        <h5>Account Type</h5>
      </div>
      <div class="mb-3 d-flex justify-content-center w-75 mx-auto">
        <%= f.select :type, Admin::USER_TYPE_OPTIONS, class: 'form-select' %>
      </div>
    </div>
  </div>
</div>
<% end %>
  

app/views/admins/pending.html.erb
<div class="d-flex flex-column dashboard">
  <div class="mb-3">
    <%= link_to root_path, :class => "mt-3 text-start fs-4" do %>
      <i class="fas fa-arrow-left text-dark"></i>
    <% end %>
  </div>
  <h1>Pending Users</h1>
  <div class="table-responsive">
    <table class="table table-hover mt-3">
      <thead class="table-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Type</th>
          <th scope="col">Email</th>
          <th scope="col">Status</th>
          <th scope="col"></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <% @users.each_with_index do |user, index| %>
      <tbody>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= user.name %></td>
          <td><%= user.type %></td>
          <td><%= user.email %></td>
          <td><span class="text-warning"><%= "Pending" unless user.approved == true%> </span></td>
          <td class="text-center">
            <%= link_to 'View User', admins_show_user_path(user.id), :class => "btn btn-action btn-sm btn-secondary text-white" %>
          </td>
          <td class="text-center">
            <%= link_to 'Approve User', admins_approve_user_path(user.id), :class => "btn btn-action btn-sm btn-success text-white" %>
          </td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/admins/show_user.html.erb
<div class="container height-100 d-flex justify-content-center align-items-center row">
  <div class="card card-user text-center">
    <%= link_to admins_index_path, :class => "mt-3 text-start" do %>
      <i class="fas fa-arrow-left text-dark"></i>
    <% end %>
    <div class="py-4 p-2">
      <div>
        <% if @user.avatar.attached? %>
          <%= image_tag @user.avatar.variant(resize: "150x150!"), class:  "rounded-circle mt-3 mb-2" %>
        <% else %>
          <%= image_tag("default_profile.jpg", class: "rounded-circle mt-3 mb-2", height: '150', width: '150') %>
        <% end %>
      </div>
      <div class="mt-3 d-flex flex-row justify-content-center">
        <h5><%= @user.name %></h5> 
      </div> 
      <span class="badge bg-dark mb-2"><%= @user.type %></span><br>
      <span>Member since <%= @user.created_at.strftime("%B %Y") %></span>
      <div class="mt-2">
        <%= link_to 'Edit', admins_edit_user_path(@user.id), :class => "btn btn-action btn-sm btn-warning text-dark ms-1" %> 
        <% if @user.approved == false %>
            <%= link_to 'Approve', admins_approve_user_path(@user.id), :class => "btn btn-action btn-sm btn-success text-light" %>
        <% end %>
      </div>
    </div>
  </div>
</div>