config/routes.rb
Rails.application.routes.draw do
  devise_for :buyers
  devise_for :brokers
  devise_for :admins
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"
  get 'home/transactions'
  get 'portfolio/broker' => 'home#broker_portfolio', as: 'home_broker_portfolio'
  get 'portfolio/buyer' => 'home#buyer_portfolio', as: 'home_buyer_portfolio'
  get 'portfolio/broker/stocks' => 'home#broker_show_stocks', as: 'home_broker_show_stocks'
  get 'portfolio/buyer/stocks' => 'home#buyer_show_stocks', as: 'home_buyer_show_stocks'

  post 'stocks/search' => 'stocks#create', as: 'stocks_create'
  get 'stocks/show/:id' => 'stocks#show', as: 'stocks_show'
  get 'stocks/chart' => 'stocks#chart', as: 'stocks_chart'
  put 'stocks/broker/add/:id' => 'stocks#broker_add', as: 'stocks_broker_add'
  get 'stocks/buyer/new/:id' => 'stocks#buy', as: 'stocks_buy'
  post 'stocks/buyer/create/:id' => 'stocks#buyer_create', as: 'stocks_buyer_create'
  delete 'stocks/show/:id' => 'stocks#broker_delete', as: 'stocks_broker_delete'

  get 'admins/index'
  get 'admins/new/user'  => 'admins#new_user',   as: 'admins_new_user'
  post 'admins/new/user' => 'admins#create_user', as: 'admins_create_user'
  get 'admins/show/user/:id' => 'admins#show_user', as: 'admins_show_user'
  get 'admins/edit/user/:id' => 'admins#edit_user', as: 'admins_edit_user'
  put 'admins/edit/user/:id' => 'admins#update_user', as: 'admins_update_user'
  delete 'admins/edit/user/:id' => 'admins#cancel_user', as: 'admins_cancel_user'
  get 'admins/:id/approve'=> 'admins#approve_user', as: 'admins_approve_user'
  get 'admins/pending' => 'admins#pending', as: 'admins_pending'
end

app/models/stock.rb
class Stock < ApplicationRecord
  validates :symbol, presence: true
  validates :name, presence: true

  has_many :user_stocks, dependent: :destroy
  has_many :users, through: :user_stocks
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  include StockApi

  before_action :authenticate_user!

  def create
    @quote = @client.quote(stock_params)
    @company = @client.company(stock_params)
    @logo = @client.logo(stock_params)
    @stock = Stock.find_or_create_by(symbol: stock_params,
                                    name: @client.company(stock_params).company_name)

    @stock.latest_price = @quote.latest_price
    @stock.change = @quote.change
    @stock.percent = @quote.change_percent_s
    @stock.wk_high = @quote.week_52_high
    @stock.wk_low = @quote.week_52_low
    @stock.volume = @quote.iex_volume
    @stock.avg_volume = @quote.avg_total_volume
    @stock.mkt_cap = @quote.market_cap
    @stock.pe_ratio = @quote.pe_ratio
    @stock.logo = @logo.url
    @stock.description = @company.description

    if @stock.save
      redirect_to stocks_show_path(@stock)
    else
      render :search
    end
  rescue IEX::Errors::SymbolNotFoundError => e
    flash[:alert] = e.message
    redirect_to home_broker_portfolio_path
  end

  def show
    @stock = Stock.find(stock_id_params)
    @news = @client.news(@stock.symbol)
    @news_list = [@news.fifth, @news.second, @news.last]
    @gain_loss = if @stock.percent.include?('-')
                   'loss'
                 else
                   'gain'
                 end
  end

  def broker_add
    @stock = Stock.find(stock_id_params)
    @stock.users << current_user
    @stock.save
    redirect_to stocks_show_path(@stock)
  end

  def buy
    @user_stock = UserStock.find(user_id_params)
    @stock = @user_stock.stock
    @broker = @user_stock.user
  end

  def buyer_create
    @user_stock = UserStock.find(user_id_params)
    @stock = @user_stock.stock
    @broker = @user_stock.user
    @buyer_stock = BuyerStock.create(buyer_stock_params)
    @buyer_stock.user_id = current_user.id
    @buyer_stock.user_stock_id = @user_stock.id
    if @buyer_stock.save
      @transaction = current_user.transactions.create(stock_id: @stock.id, broker_id: @broker.id, quantity: @buyer_stock.quantity,
                                                      price: @buyer_stock.price, total: (@buyer_stock.quantity * @buyer_stock.price))
      @transaction.save
      flash[:notice] = "You have successfully purchased #{@buyer_stock.quantity} shares of #{@stock.symbol.upcase}"
      redirect_to home_transactions_path
    else
      render :buyer_new
    end
  end

  private

  def stock_params
    params[:symbol]
  end

  def stock_id_params
    params[:id]
  end

  def user_id_params
    params[:id]
  end

  def buyer_stock_params
    params.permit(:user_id, :user_stock_id, :quantity, :price)
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/buy.html.erb
<div class="d-flex flex-column dashboard animate slideIn">
  <h1>Buy Stocks</h1>
  <div class="mt-2">
    <%= link_to "#", :class => "mt-3 text-start fs-4 back-btn" do %>
      <i class="fas fa-arrow-left text-dark"></i>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-5 offset-md-3">
      <div class="card mx-auto mt-5">
        <div class="card-body pt-4 mx-auto">
          <%= form_with(url: stocks_buyer_create_path, method: :post, local: true) do |f| %>
            <div>
              <p class="fw-bold"><%= @stock.name %> (<%= @stock.symbol.upcase %>)</p>
              <p> Broker: <%= @broker.name  %> </p> 
            </div>
            <div class="mb-3 form-floating">
              <%= f.number_field :quantity, min: 1, step: 1, class: "form-control shadow-none", placeholder: 'Input qty.' %>
              <%= f.label "Qty.", class: "p-3" %>
            </div>

            <div class="mb-4 form-floating">
              <%= f.text_field :price, value: @stock.latest_price, readonly: true, class: "form-control shadow-none", placeholder: 'Stock Price' %>
              <%= f.label "Current price", class: "form-label" %>
            </div>

            <div class="mt-4 mb-3 text-center">
              <%= f.submit "Buy", class: "btn btn-md btn-primary fw-bold" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).on("click", ".back-btn", function(event) {
  event.preventDefault()
  history.back()
})
</script>

app/views/stocks/show.html.erb
<div class="d-flex flex-column dashboard">
  <h1>Search Stocks</h1>
  <div class="w-50 mt-3 mb-4">
    <%= form_with method: :post, url: stocks_create_path , local:true do |f| %>
    <div class=" input-group input-group-sm">
      <%= f.text_field :symbol, :class => 'form-control search-bar fs-5 ps-3', placeholder: 'Search by stock' %>
      <span class="input-group-text bg-dark border-dark" id="basic-addon2">
      <%= f.button :button, :class => 'btn btn-sm' do %>
        <lord-icon
          src="https://cdn.lordicon.com/msoeawqm.json"
          trigger="hover"
          colors="primary:#ffffff,secondary:#16c72e"
          stroke="100"
          scale="64"
          style="width:32px;height:32px">
        </lord-icon>
      <% end %>
      </span>
    </div>
    <% end %>
  </div>
  <div class="card animate slideIn mb-5"> <!--show-card -->
    <div class="card-body px-5 pt-4">
      <% if broker_signed_in? %>
        <div class="mb-4">
          <%= link_to home_broker_show_stocks_path, :class => "mt-3 text-start fs-4" do %>
            <i class="fas fa-arrow-left text-dark"></i>
          <% end %>
        </div>
      <% elsif buyer_signed_in? %>
        <div class="mb-4">
          <%= link_to home_buyer_show_stocks_path, :class => "mt-3 text-start fs-4" do %>
            <i class="fas fa-arrow-left text-dark"></i>
          <% end %>
        </div>
      <% end %>
      <div class="d-flex justify-content-between">
        <div>
          <h1><%= number_to_currency(@stock.latest_price) %></h1>
        </div>
        <div>
          <img src="<%= @stock.logo %>" height="50">
        </div>
      </div>
      <div class="d-flex justify-content-between">
        <div>
          <p class="stock-change stock-<%= @gain_loss %>"><%= number_to_currency(@stock.change) %> (<%= @stock.percent %>) <span class="text-secondary">TODAY</span></p>
          <% if broker_signed_in? %>
            <% if current_user.stocks.include?(@stock) %>
              <button type="button" class="btn btn-success btn-sm fw-bold" disabled>&#x2714; Stock Added</button>
            <% else %>
              <%= link_to stocks_broker_add_path(@stock), method: :put, class: 'btn btn-success btn-sm fw-bold shadow-none', id: 'addStockId' do %>
                Add Stock
                <lord-icon
                  src="https://cdn.lordicon.com/mecwbjnp.json"
                  trigger="hover"
                  colors="primary:#ffffff,secondary:#d1fad7"
                  stroke="100"
                  scale="80"
                  style="width:32px;height:32px">
                </lord-icon>
              <% end %>
            <% end %>
          <% elsif buyer_signed_in? %>
            <button id="buy-broker-btn" class='btn btn-success btn-sm fw-bold shadow-none'> 
              Buy from Broker 
              <lord-icon
                  src="https://cdn.lordicon.com/uukerzzv.json"
                  trigger="loop-on-hover"
                  colors="primary:#ffffff,secondary:#a5e830"
                  stroke="100"
                  style="width:32px;height:32px">
              </lord-icon>
            </button>
          <% end %>
          </div>
        <div>
          <h5 class="text-end fs-4"><%= @stock.symbol.upcase %></h5>
          <h6 class="text-secondary fs-5"><%= @stock.name %></h6>
        </div>
      </div>
      <hr>
      <div class="row mt-4 mb-5">
        <div class="col-6">
          <h5 class="fw-bolder mb-4">Stats</h5>
          <div class="row mb-3 mt-3">
            <div class="col-3">
              <small class="fw-bold text-secondary">OPEN</small>
            </div>
            <div class="col-3">
              <small class="fw-bold">
                <% if !(@stock.ohlc_high.nil?)%>
                  <%= number_to_currency(@stock.ohlc_open) %>
                <% else %>
                  -
                <% end %>
              </small>
            </div>
            <div class="col-3">
              <small class="fw-bold text-secondary">VOLUME</small>
            </div>
            <div class="col-3">
              <small class="fw-bold">
              <% if !(@stock.volume.nil?)%>
                <%= number_to_human(@stock.volume, :format => '%n %u', :units => { :thousand => 'K', :million => 'M', :billion => 'B' }) %>
              <% else %>
                -
              <% end %>   
              </small>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col-3">
              <small class="fw-bold text-secondary">HIGH</small>
            </div>
            <div class="col-3">
              <small class="fw-bold">
                <% if !(@stock.ohlc_high.nil?)%>
                  <%= number_to_currency(@stock.ohlc_high) %>
                <% else %>
                  -
                <% end %>
              </small>
            </div>
            <div class="col-3">
              <small class="fw-bold text-secondary">AVG.VOLUME</small>
            </div>
            <div class="col-3">
              <small class="fw-bold">
              <% if !(@stock.avg_volume.nil?)%>
                <%= number_to_human(@stock.avg_volume, :format => '%n %u', :units => { :thousand => 'K', :million => 'M', :billion => 'B' }) %>
              <% else %>
               -
              <% end %>
              </small>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col-3">
              <small class="fw-bold text-secondary">LOW</small>
            </div>
            <div class="col-3">
              <small class="fw-bold">
                <% if !(@stock.ohlc_high.nil?)%>
                  <%= number_to_currency(@stock.ohlc_low) %>
                <% else %>
                  -
                <% end %>
              </small>
            </div>
            <div class="col-3">
              <small class="fw-bold text-secondary">MKT CAP</small>
            </div>
            <div class="col-3">
              <small class="fw-bold">
              <% if !(@stock.mkt_cap.nil?)%>
                <%= number_to_human(@stock.mkt_cap, :format => '%n %u', :units => { :thousand => 'K', :million => 'M', :billion => 'B' }) %>
              <% else %>
                -
              <% end %>
              </small>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col-3">
              <small class="fw-bold text-secondary">52 WK HIGH</small>
            </div>
            <div class="col-3">
              <small class="fw-bold">
              <% if !(@stock.wk_high.nil?)%>
                <%= number_to_currency(@stock.wk_high) %>
              <% else %>
                -
              <% end %>
              </small>
            </div>
            <div class="col-3">
              <small class="fw-bold text-secondary">P/E RATIO</small>
            </div>
            <div class="col-3">
              <small class="fw-bold">
              <% if !(@stock.pe_ratio.nil?)%>
                <%= @stock.pe_ratio %>
              <% else %>
                -
              <% end %>
              </small>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col-3">
              <small class="fw-bold text-secondary">52 WK LOW</small>
            </div>
            <div class="col-3">
              <small class="fw-bold">
              <% if !(@stock.wk_low.nil?)%>
                <%= number_to_currency(@stock.wk_low) %>
              <% else %>
                -
              <% end %>
              </small>
            </div>
          </div>
        </div>
        <div class="col-6 mb-4">
          <h5 class="mb-3">About</h5>
          <div>
            <small class="fs-6 text-secondary">
            <% if @stock.description.length > 250 %>
              <%= @stock.description.truncate(500) %> 
              <%= link_to 'Read More', '', class: "read-more-#{@stock.id} fw-bold" %>
              <script>
                $('.read-more-<%= @stock.id %>').on('click', function(e) {
                  e.preventDefault()
                  $(this).parent().html('<%= escape_javascript @stock.description %>')
                })
              </script>
              <% else %>
                <%= @stock.description %>
              <% end %>
            </small>
          </div>
        </div>
        <% if buyer_signed_in? %>
          <hr>
          <div class="col broker-section" id="broker">
            <h5 class="fw-bolder mb-4 mt-3">Brokers</h5>
            <div class="table-responsive mt-3">
              <table class="table table-hover mt-3">
                <thead class="table-dark">
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Broker Name</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <% @stock.user_stocks.each_with_index do | broker_stock, index | %>
                <tbody>
                  <tr>
                    <th scope="row"><%= index + 1 %></th>
                    <td><%= broker_stock.user.name %></td>
                    <td><%= link_to "Buy", stocks_buy_path(broker_stock, @stock, broker_stock.user), method: :get, class: 'btn btn-success btn-sm fw-bold' %></td>
                  </tr>
                </tbody>
                <% end %>
              </table>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <h1>News</h1>
  <div class="row mt-4 mb-5">
    <% @news_list.each do | stock_news | %>
    <div class="col-4">
      <div class="card animate slideIn">
        <div class="card-body p-4">
          <h5 class="card-title"><%= stock_news.headline %></h5>
          <p class="card-text mt-3 text-secondary">
            <% if stock_news.summary.length > 250 %>
              <%= stock_news.summary.truncate(500) %> 
              <%= link_to 'Read More', '', class: "read-more-#{@stock.id} fw-bold" %>
              <script>
                $('.read-more-<%= @stock.id %>').on('click', function(e) {
                  e.preventDefault()
                  $(this).parent().html('<%= escape_javascript stock_news.summary %>')
                })
              </script>
            <% else %>
              <%= stock_news.summary %>
            <% end %>
          </p>
          <p class="card-text"><small class="text-muted"><%= stock_news.datetime %></small></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>