config/routes.rb
Rails.application.routes.draw do
  devise_for :buyers
  devise_for :brokers
  devise_for :admins
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"
  get 'home/transactions'
  get 'portfolio/broker' => 'home#broker_portfolio', as: 'home_broker_portfolio'
  get 'portfolio/buyer' => 'home#buyer_portfolio', as: 'home_buyer_portfolio'
  get 'portfolio/broker/stocks' => 'home#broker_show_stocks', as: 'home_broker_show_stocks'
  get 'portfolio/buyer/stocks' => 'home#buyer_show_stocks', as: 'home_buyer_show_stocks'

  post 'stocks/search' => 'stocks#create', as: 'stocks_create'
  get 'stocks/show/:id' => 'stocks#show', as: 'stocks_show'
  get 'stocks/chart' => 'stocks#chart', as: 'stocks_chart'
  put 'stocks/broker/add/:id' => 'stocks#broker_add', as: 'stocks_broker_add'
  get 'stocks/buyer/new/:id' => 'stocks#buy', as: 'stocks_buy'
  post 'stocks/buyer/create/:id' => 'stocks#buyer_create', as: 'stocks_buyer_create'
  delete 'stocks/show/:id' => 'stocks#broker_delete', as: 'stocks_broker_delete'

  get 'admins/index'
  get 'admins/new/user'  => 'admins#new_user',   as: 'admins_new_user'
  post 'admins/new/user' => 'admins#create_user', as: 'admins_create_user'
  get 'admins/show/user/:id' => 'admins#show_user', as: 'admins_show_user'
  get 'admins/edit/user/:id' => 'admins#edit_user', as: 'admins_edit_user'
  put 'admins/edit/user/:id' => 'admins#update_user', as: 'admins_update_user'
  delete 'admins/edit/user/:id' => 'admins#cancel_user', as: 'admins_cancel_user'
  get 'admins/:id/approve'=> 'admins#approve_user', as: 'admins_approve_user'
  get 'admins/pending' => 'admins#pending', as: 'admins_pending'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include StockApi

  before_action :authenticate_user!, except: [:index]
  before_action :broker?, only: [:broker_portfolio]
  before_action :buyer?, only: [:buyer_portfolio]

  def index
    @admins_pending = User.where(type: 'Admin', approved: false)
    @brokers_pending = User.where(type: 'Broker', approved: false)
    @buyers_pending = User.where(type: 'Buyer', approved: false)

    @transactions = Transaction.all

    if broker_signed_in?
      redirect_to home_broker_portfolio_path
    elsif buyer_signed_in?
      redirect_to home_buyer_portfolio_path
    end
  end

  def broker_portfolio
    @stocks = current_user.stocks
    @stock = Stock.new
    @top_list = @client.stock_market_list(:mostactive)
    @transactions = Transaction.where(broker_id: current_user.id)
  end

  def buyer_portfolio
    @buyer_stocks = current_user.user_stocks
    @buyer_total_stocks = BuyerStock.all
    @transactions = current_user.transactions
  end

  def broker_show_stocks
    @stocks = current_user.stocks
  end

  def buyer_show_stocks
    @buyer_stocks = current_user.user_stocks
  end

  def transactions
    case current_user.type
    when 'Broker'
      @transactions = Transaction.where(broker_id: current_user.id)
      @method = 'Sell'
    when 'Buyer'
      @transactions = current_user.transactions
      @method = 'Buy'
    when 'Admin'
      @transactions = Transaction.all
      @method = 'Buy'
    end
  end

  private

  def broker?
    redirect_to root_path unless current_user.type == 'Broker'
  end

  def buyer?
    redirect_to root_path unless current_user.type == 'Buyer'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_dashboard.html.erb
<div class="d-flex flex-column dashboard animate slideIn">
  <h1>Dashboard</h1>
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-2 mb-1 px-3"> 
    <%= link_to admins_new_user_path, class: "btn btn-dark btn-sm me-2 rounded-pill add-user-btn fw-bold", id: "addUserId" do %>
      <span class="fas fa-plus me-2"></span> Add User
    <% end %>
    <div class="btn-group">
      <button type="button" class="btn btn-sm btn-share">Share</button> 
      <button type="button" class="btn btn-sm btn-export">Export</button>
    </div>
  </div>
  <div class="row justify-content-md-center px-3 pt-1 g-5">
    <div class="col-12 col-sm-4 col-xl-4">
      <div class="card admin-card shadow-sm" id="usersId">
        <div class="card-body">
          <div class="row d-block d-xl-flex align-items-center">
            <div class="col-12 col-xl-5 text-xl-center mb-3 mb-xl-0 d-flex align-items-center justify-content-xl-center">
              <div class="icon-shape icon-shape-primary me-4 me-sm-0">
                <i class="fas fa-user-friends"></i>
              </div>
              <div class="d-sm-none">
                <h5><a href="<%= admins_index_path %>" class="text-dark stretched-link"></a>Users</h5>
                <h3 class="mb-1"><%= User.count %></h3>
              </div>
            </div>
            <div class="col-12 col-xl-7 px-xl-0">
              <div class="d-none d-sm-block">
                <h5><a href="<%= admins_index_path %>" class="text-dark stretched-link"></a>Users</h5>
                <h3 class="mb-1"><%= User.count %></h3>
              </div>
              <small>As of today, <%= Date.today %></small>
              <div class="small mt-2">
                <span class="fas fa-angle-up text-admin-success"></span> 
                <span class="text-admin-success fw-bold">0.1%</span> 
                Since last month
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-sm-4 col-xl-4">
      <div class="card admin-card shadow-sm">
        <div class="card-body">
          <div class="row d-block d-xl-flex align-items-center">
            <div class="col-12 col-xl-5 text-xl-center mb-3 mb-xl-0 d-flex align-items-center justify-content-xl-center">
              <div class="icon-shape icon-shape-secondary me-4 me-sm-0">
                <i class="fas fa-cash-register"></i>
              </div>
              <div class="d-sm-none">
                <h5><a href="<%= home_transactions_path %>" class="stretched-link"></a>Transactions</h5>
                <h3 class="mb-1"><%= @transactions.count %></h3>
              </div>
            </div>
            <div class="col-12 col-xl-7 px-xl-0">
              <div class="d-none d-sm-block">
                <h5><a href="<%= home_transactions_path  %>" class="stretched-link"></a>Transactions</h5>
                <h3 class="mb-1"><%= @transactions.count %></h3>
              </div>
              <small>This month</small>
              <div class="small mt-2">
                <span class="fas fa-angle-up text-admin-success"></span> 
                <span class="text-admin-success fw-bold">28.2%</span> 
                Since last month
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-sm-4 col-xl-4">
      <div class="card admin-card shadow-sm">
        <div class="card-body">
          <div class="row d-block d-xl-flex align-items-center">
            <div class="col-12 col-xl-5 text-xl-center mb-3 mb-xl-0 d-flex align-items-center justify-content-xl-center">
              <div class="icon-shape icon-shape-info me-4 me-sm-0">
                <i class="fas fa-chart-pie"></i>
              </div>
              <div class="d-sm-none">
                <h5 class="ms-1"><a href="<%= admins_pending_path  %>" class="stretched-link"></a>Pending</h5>
              </div>
            </div>
            <div class="col-12 col-xl-7 px-xl-0">
              <div class="d-none d-sm-block">
                <h5 class="ms-1"><a href="<%= admins_pending_path %>" class="stretched-link"></a>Pending</h5>
              </div>
              <h6 class="text-secondary admin-text">
                <span class="icon w-20 icon-xs icon-secondary"><i class="fas fa-user-shield"></i></span> 
                Admin <strong><%= @admins_pending.count %></strong>
              </h6>
              <h6 class="text-secondary admin-text">
                <span class="icon w-20 icon-xs icon-secondary"><i class="fas fa-business-time"></i></span> 
                Broker <strong><%= @brokers_pending.count %></strong>
              </h6>
              <h6 class="text-secondary admin-text">
                <span class="icon w-20 icon-xs icon-secondary"><i class="fab fa-ello"></i></span> 
                &nbsp;Buyer <strong><%= @buyers_pending.count %></strong>
              </h6>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/broker_portfolio.html.erb
<div class="d-flex flex-column dashboard animate slideIn">
  <h1><%= current_user.name%>'s Portfolio</h1>
  <div class="w-50 mt-3 mb-4">
  <%= form_with method: :post, url: stocks_create_path , local:true do |f| %>
  <div class=" input-group input-group-sm">
    <%= f.text_field :symbol, :class => 'form-control search-bar fs-5 ps-3', placeholder: 'Search by stock' %>
    <span class="input-group-text bg-dark border-dark" id="searchId">
    <%= f.button :button, :class => 'btn btn-sm' do %>
      <lord-icon
        src="https://cdn.lordicon.com/msoeawqm.json"
        trigger="hover"
        colors="primary:#ffffff,secondary:#16c72e"
        stroke="100"
        scale="64"
        style="width:32px;height:32px">
      </lord-icon>
    <% end %>
    </span>
  </div>
  <% end %>
</div>
  <div class="row justify-content-md-center px-1 pt-1 g-5">
    <div class="col-12 col-sm-12 col-xl-4">
      <div class="card portfolio-card shadow-sm">
        <div class="card-body ps-4">
          <h2 class="h5"><a href="<%= home_broker_show_stocks_path %>" class="text-dark stretched-link"></a>My Stocks</h2>
          <div class="d-block">
            <div class="d-flex align-items-center pt-3 me-5">
              <div class="icon icon-shape icon-sm icon-shape-success rounded me-3">
                <span class="fas fa-chart-bar">
                </span>
              </div>
              <div class="d-block">
                <label class="mb-0">Total Stocks</label>
                <h4 class="mb-0 fw-bold"><%= current_user.stocks.count %></h4>
              </div>
            </div>
            <div class="d-flex align-items-center pt-3">
              <div class="icon icon-shape icon-sm icon-shape-quaternary rounded me-3">
                <span class="fas fa-chart-area"></span>
              </div>
              <div class="d-block">
                <label class="mb-0">No. of Buyers</label>
                <h4 class="mb-0 fw-bold"><%= @transactions.distinct.count(:user_id) %></h4>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-sm-12 col-xl-4">
      <div class="card portfolio-card shadow-sm">
        <div class="card-body ps-4">
          <h2 class="h5"><a href="<%= home_transactions_path %>" class="text-dark stretched-link"></a>Transactions</h2>
          <div class="d-block broker-card">
            <div class="d-flex align-items-center pt-3 me-5">
              <div class="d-block">
                <div class="h6 fw-normal text-gray mb-2">
                  Total orders
                </div>
                <h2 class="h3 fw-bold"><%= @transactions.count %></h2>
                <div class="small mt-2">
                  <span class="fas fa-angle-up text-success"></span>
                  <span class="text-success fw-bold">18.2%</span>
                </div>
                <div class="small mt-2">
                  <span class="fw-normal">As of today, <%= Date.today %></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-sm-12 col-xl-4">
      <div class="col-12 px-0 mb-4">
        <div class="card shadow-sm">
          <div class="card-body ps-4">
            <h2 class="h5">Most Active</h2>
            <% @top_list.each do | stock | %> 
            <div class="d-flex align-items-center justify-content-between border-bottom border-light mt-4 pe-4 ps-1 py-2">
              <div>
                <h6 class="mb-0">
                  <%= stock.symbol %>
                </h6>
                <div class="small card-stats text-<%= stock.change_percent_s.include?('-') ? 'danger' : 'success' %>">
                  <%= stock.change_percent_s %><i class="fas fa-caret-<%= stock.change_percent_s.include?('-') ? 'down' : 'up' %>"></i>
                </div>
              </div>
              <div>
                <span class="fw-bold"><%= number_to_currency(stock.latest_price) %></span>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/broker_show_stocks.html.erb
<div class="d-flex flex-column dashboard">
  <h1>My Stocks</h1>
  <div class="w-50 mt-3 mb-4">
    <%= form_with method: :post, url: stocks_create_path , local:true do |f| %>
    <div class=" input-group input-group-sm">
      <%= f.text_field :symbol, :class => 'form-control search-bar fs-5 ps-3', placeholder: 'Search by stock' %>
      <span class="input-group-text bg-dark border-dark" id="basic-addon2">
      <%= f.button :button, :class => 'btn btn-sm' do %>
        <lord-icon
          src="https://cdn.lordicon.com/msoeawqm.json"
          trigger="hover"
          colors="primary:#ffffff,secondary:#16c72e"
          stroke="100"
          scale="64"
          style="width:32px;height:32px">
        </lord-icon>
      <% end %>
      </span>
    </div>
    <% end %>
  </div>
  <div class="mt-2">
    <%= link_to home_broker_portfolio_path, :class => "mt-3 text-start fs-4" do %>
      <i class="fas fa-arrow-left text-dark"></i>
    <% end %>
  </div>
  <div class="row row-cols-1 row-cols-md-4 g-4 mt-4">
    <% @stocks.each do | stock | %>
    <div class="col mb-3">
      <div class="card text-white bg-dark stocks-card">
        <div class="card-body">
          <h3 class="card-title stocks-title mb-0"><a href="<%= stocks_show_path(stock.id) %>" class="stretched-link"></a><%= stock.symbol.upcase %> </h3>
          <small><%= stock.name %></small>
          <h5 class="card-text mt-4 fs-4"><%= number_to_currency(stock.latest_price) %></h5>
          <div class="row">
            <div class="col">
              <p class="stock-change stock-<%= stock.percent.include?('-') ? 'loss' : 'gain'  %> mb-0"><%= number_to_currency(stock.change) %> (<%= stock.percent %>) <i class="fas fa-caret-<%= stock.percent.include?('-') ? 'down' : 'up'  %>"></i></p><br>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/home/buyer_portfolio.html.erb
<div class="d-flex flex-column dashboard animate slideIn">
  <h1 class="animate slideIn"><%= current_user.name%>'s Portfolio</h1>
  <div class="w-50 mt-3 mb-4">
  <%= form_with method: :post, url: stocks_create_path , local:true do |f| %>
    <div class=" input-group input-group-sm">
      <%= f.text_field :symbol, :class => 'form-control search-bar fs-5 ps-3', placeholder: 'Search by stock' %>
      <span class="input-group-text bg-dark border-dark" id="searchId">
      <%= f.button :button, :class => 'btn btn-sm shadow-none' do %>
        <lord-icon
          src="https://cdn.lordicon.com/msoeawqm.json"
          trigger="hover"
          colors="primary:#ffffff,secondary:#16c72e"
          stroke="100"
          scale="64"
          style="width:32px;height:32px">
        </lord-icon>
      <% end %>
      </span>
    </div>
  <% end %>
</div>
<div class="row justify-content-md-center px-1 pt-1 g-5 buyer-row mt-4">
  <div class="col-12 col-sm-12 col-xl-4">
    <div class="card buyer-card shadow-sm">
      <div class="card-body ps-4">
        <h2 class="h5"><a href="<%= home_buyer_show_stocks_path %>" class="text-dark stretched-link"></a>My Stocks</h2>
        <div class="d-block">
          <div class="d-flex align-items-center pt-3 me-5">
            <div class="icon icon-shape icon-sm icon-shape-success rounded me-3">
              <span class="fas fa-chart-bar">
              </span>
            </div>
            <div class="d-block">
              <label class="mb-0">Total Stocks</label>
                <h4 class="mb-0 fw-bold"><%= @buyer_total_stocks.distinct.count(:user_stock_id) %></h4>
            </div>
          </div>
          <div class="d-flex align-items-center pt-3">
            <div class="icon icon-shape icon-sm icon-shape-quaternary rounded me-3">
              <span class="fas fa-coins"></span>
            </div>
            <div class="d-block">
              <label class="mb-0">Total Earnings</label>
              <% @buyer_stocks.group(:stock_id).sum(:quantity).each do |id, sum| %>
                <% stock = Stock.find(id) %>
              <h4 class="mb-0 fw-bold"><%= number_to_currency(stock.latest_price.to_f * sum) %></h4>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-12 col-sm-12 col-xl-4">
    <div class="card buyer-card shadow-sm">
      <div class="card-body ps-4">
        <h2 class="h5"><a href="<%= home_transactions_path %>" class="text-dark stretched-link"></a>Transactions</h2>
        <div class="d-block broker-card">
          <div class="d-flex align-items-center pt-3 me-5">
            <div class="d-block">
              <div class="h6 fw-normal text-gray mb-2">
                Total orders
              </div>
              <h2 class="h3 fw-bold"><%= @transactions.count %></h2>
              <div class="small mt-2">
                <span class="fas fa-angle-up text-success"></span>
                <span class="text-success fw-bold">18.2%</span>
              </div>
              <div class="small mt-2">
                <span class="fw-normal">As of today, <%= Date.today %></span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div> 
  </div>
  <hr class="mt-5">
</div>

app/views/home/buyer_show_stocks.html.erb
<div class="d-flex flex-column dashboard">
  <h1>My Stocks</h1>
  <div class="w-50 mt-3 mb-4">
    <%= form_with method: :post, url: stocks_create_path , local:true do |f| %>
    <div class=" input-group input-group-sm">
      <%= f.text_field :symbol, :class => 'form-control search-bar fs-5 ps-3', placeholder: 'Search by stock' %>
      <span class="input-group-text bg-dark border-dark" id="basic-addon2">
      <%= f.button :button, :class => 'btn btn-sm' do %>
        <lord-icon
          src="https://cdn.lordicon.com/msoeawqm.json"
          trigger="hover"
          colors="primary:#ffffff,secondary:#16c72e"
          stroke="100"
          scale="64"
          style="width:32px;height:32px">
        </lord-icon>
      <% end %>
      </span>
    </div>
    <% end %>
  </div>
  <div class="mt-2">
    <%= link_to home_buyer_portfolio_path, :class => "mt-3 text-start fs-4" do %>
      <i class="fas fa-arrow-left text-dark"></i>
    <% end %>
  </div>
  <div class="row row-cols-1 row-cols-md-4 g-4 mt-4">
    <% @buyer_stocks.group(:stock_id).sum(:quantity).each do |id, sum| %>
      <% stock = Stock.find(id) %>
      <div class="col mb-3">
        <div class="card text-white bg-dark stocks-card">
          <div class="card-body">
            <h3 class="card-title stocks-title mb-0"><a href="<%= stocks_show_path(stock.id) %>" class="stretched-link"></a><%= stock.symbol.upcase %> </h3>
            <small><%= stock.name %></small>
            <h5 class="card-text mt-4 fs-4"><%= number_to_currency(stock.latest_price) %></h5>
            <div class="row">
              <div class="col">
                <p class="stock-change stock-<%= stock.percent.include?('-') ? 'loss' : 'gain'  %> mb-0"><%= number_to_currency(stock.change) %> (<%= stock.percent %>) <i class="fas fa-caret-<%= stock.percent.include?('-') ? 'down' : 'up'  %>"></i></p><br>
                <p class="m-0">Total Shares: <%= sum %></p>
                <p>Current Value: <%= number_to_currency(stock.latest_price.to_f * sum) %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<% if admin_signed_in? %>
  <%= render partial: "dashboard", locals: {index: true} %>
<% end %>

app/views/home/transactions.html.erb
<div class="d-flex flex-column dashboard">
   <% if admin_signed_in? %>
      <div class="mb-3">
        <%= link_to root_path, :class => "mt-3 text-start fs-4" do %>
          <i class="fas fa-arrow-left text-dark"></i>
        <% end %>
      </div>
    <% elsif current_user.type == "Broker" %>
      <div class="mb-3">
        <%= link_to home_broker_portfolio_path, :class => "mt-3 text-start fs-4" do %>
          <i class="fas fa-arrow-left text-dark"></i>
        <% end %>
      </div>
    <% else %>
      <div class="mb-3">
        <%= link_to home_buyer_portfolio_path, :class => "mt-3 text-start fs-4" do %>
          <i class="fas fa-arrow-left text-dark"></i>
        <% end %>
      </div>
    <% end %>
    <h1>Transactions</h1>
    <div class="table-responsive mt-3">
      <table class="table table-hover mt-3">
        <thead class="table-dark">
          <tr>
            <th scope="col">#</th>
            <% if current_user.type == "Admin" %>
              <th scope="col">Buyer</th>
              <th scope="col">Broker</th>
            <% end %>
            <th scope="col">Symbol</th>
            <th scope="col">Side</th>
            <th scope="col">Quantity</th>
            <th scope="col">Price</th>
            <th scope="col">Total</th>
            <th scope="col">Time</th>
          </tr>
        </thead>
        <% @transactions.each_with_index do |transaction, index| %>
        <tbody>
          <tr>
            <th scope="row"><%= index + 1 %></th>
            <% if current_user.type == "Admin" %>
              <td><%= transaction.user.name %></td>
              <td><%= Broker.find(transaction.broker_id).name %></td>
            <% end %>
            <td><%= Stock.find(transaction.stock_id).symbol.upcase %></td>
            <td><%= @method %></td>
            <td><%= transaction.quantity %></td>
            <td>
              <% if current_user.type == "Broker" || "Admin" %>
                <%= number_to_currency(transaction.price)%>
              <% elsif current_user.type == "Buyer" %>
                <%= transaction.price %>
              <% end %>
            </td>
            <td><%= number_to_currency(transaction.total) %></td>
            <td><%= transaction.created_at.strftime("%B %d %Y, %l:%M%P") %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
</div>