config/routes.rb
Rails.application.routes.draw do
  devise_for :buyers
  devise_for :brokers
  devise_for :admins
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"
  get 'home/transactions'
  get 'portfolio/broker' => 'home#broker_portfolio', as: 'home_broker_portfolio'
  get 'portfolio/buyer' => 'home#buyer_portfolio', as: 'home_buyer_portfolio'
  get 'portfolio/broker/stocks' => 'home#broker_show_stocks', as: 'home_broker_show_stocks'
  get 'portfolio/buyer/stocks' => 'home#buyer_show_stocks', as: 'home_buyer_show_stocks'

  post 'stocks/search' => 'stocks#create', as: 'stocks_create'
  get 'stocks/show/:id' => 'stocks#show', as: 'stocks_show'
  get 'stocks/chart' => 'stocks#chart', as: 'stocks_chart'
  put 'stocks/broker/add/:id' => 'stocks#broker_add', as: 'stocks_broker_add'
  get 'stocks/buyer/new/:id' => 'stocks#buy', as: 'stocks_buy'
  post 'stocks/buyer/create/:id' => 'stocks#buyer_create', as: 'stocks_buyer_create'
  delete 'stocks/show/:id' => 'stocks#broker_delete', as: 'stocks_broker_delete'

  get 'admins/index'
  get 'admins/new/user'  => 'admins#new_user',   as: 'admins_new_user'
  post 'admins/new/user' => 'admins#create_user', as: 'admins_create_user'
  get 'admins/show/user/:id' => 'admins#show_user', as: 'admins_show_user'
  get 'admins/edit/user/:id' => 'admins#edit_user', as: 'admins_edit_user'
  put 'admins/edit/user/:id' => 'admins#update_user', as: 'admins_update_user'
  delete 'admins/edit/user/:id' => 'admins#cancel_user', as: 'admins_cancel_user'
  get 'admins/:id/approve'=> 'admins#approve_user', as: 'admins_approve_user'
  get 'admins/pending' => 'admins#pending', as: 'admins_pending'
end

app/views/layouts/_admin_nav.html.erb
<ul class="navbar-nav me-auto mb-2 mb-md-0">
  <li class="nav-item dropdown mx-2">
    <a class="nav-link" aria-current="page" href="<%= root_path %>" role="button" aria-expanded="false">Home</a>
  </li>
  <li class="nav-item dropdown mx-2">
    <a class="nav-link" aria-current="page" href="#" id="navbarDropdownMenuLink2" role="button" data-bs-toggle="dropdown" aria-expanded="false">Users <i class="fas fa-angle-down admin-dropdown"></i></a>
    <ul class="dropdown-menu animate slideIn" aria-labelledby="navbarDropdownMenuLink2">
        <li><a class="dropdown-item" href="<%= admins_new_user_path %>">Add User</a></li>
        <li><a class="dropdown-item" href="<%= admins_index_path %>">See all Users</a></li>
    </ul>
  </li>
  <li class="nav-item mx-2">
    <a class="nav-link" aria-current="page" href="<%= home_transactions_path %>" id="navbarDropdownMenuLink3" role="button" aria-expanded="false">Transactions</a>
  </li>
</ul>

app/views/layouts/_broker_nav.html.erb
<ul class="navbar-nav me-auto mb-2 mb-md-0">
  <li class="nav-item dropdown mx-2">
    <a class="nav-link" aria-current="page" href="<%= home_broker_portfolio_path %>" role="button" aria-expanded="false">Home</a>
  </li>
  <li class="nav-item dropdown mx-2">
    <a class="nav-link" aria-current="page" href="#" id="navbarDropdownMenuLink2" role="button" data-bs-toggle="dropdown" aria-expanded="false">Stocks <i class="fas fa-angle-down broker-dropdown"></i></a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink2">
        <li><a class="dropdown-item" href="<%= home_broker_show_stocks_path %>">My Stocks</a></li>
        <li><a class="dropdown-item" href="#">News</a></li>
    </ul>
  </li>
  <li class="nav-item dropdown mx-2">
    <a class="nav-link" aria-current="page" href="<%= home_transactions_path %>" id="navbarDropdownMenuLink3" role="button" aria-expanded="false">Transactions</a>
  </li>
</ul>

app/views/layouts/_buyer_nav.html.erb
<ul class="navbar-nav me-auto mb-2 mb-md-0">
  <li class="nav-item dropdown mx-2">
    <a class="nav-link" aria-current="page" href="<%= home_buyer_portfolio_path %>" role="button" aria-expanded="false">Home</a>
  </li>
  <li class="nav-item dropdown mx-2">
    <a class="nav-link" aria-current="page" href="#" id="navbarDropdownMenuLink2" role="button" data-bs-toggle="dropdown" aria-expanded="false">Stocks <i class="fas fa-angle-down"></i></a>
    <ul class="dropdown-menu animate slideIn" aria-labelledby="navbarDropdownMenuLink2">
        <li><a class="dropdown-item" href="<%= home_buyer_show_stocks_path %>">My Stocks</a></li>
        <li><a class="dropdown-item" href="#">News</a></li>
    </ul>
  </li>
  <li class="nav-item dropdown mx-2">
    <a class="nav-link" aria-current="page" href="<%= home_transactions_path %>" id="navbarDropdownMenuLink3" role="button" aria-expanded="false">Transactions</a>
  </li>
</ul>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-light fixed-top px-5 pt-4">
    <div class="container-fluid">
      <a class="navbar-brand" href="<%= root_path %>">Stak</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
      <% if admin_signed_in? %>
        <%= render 'layouts/admin_nav' %>
      <% elsif broker_signed_in? %>
        <%= render 'layouts/broker_nav' %>
      <% elsif buyer_signed_in? %>
        <%= render 'layouts/buyer_nav' %>
      <% else %>
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item dropdown mx-2">
            <a class="nav-link" aria-current="page" href="#" id="navbarDropdownMenuLink1" role="button" data-bs-toggle="dropdown" aria-expanded="false">Products <i class="fas fa-angle-down"></i></a>
            <ul class="dropdown-menu animate slideIn" aria-labelledby="navbarDropdownMenuLink1">
              <li><a class="dropdown-item" href="#">Stocks & Funds</a></li>
              <li><a class="dropdown-item" href="#">Futures</a></li>
              <li><a class="dropdown-item" href="#">Crypto</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown mx-2">
            <a class="nav-link" aria-current="page" href="#" id="navbarDropdownMenuLink2" role="button" data-bs-toggle="dropdown" aria-expanded="false">Learn <i class="fas fa-angle-down"></i></a>
            <ul class="dropdown-menu animate slideIn" aria-labelledby="navbarDropdownMenuLink2">
              <li><a class="dropdown-item" href="#">Investing basics</a></li>
              <li><a class="dropdown-item" href="#">Blockchain</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown mx-2">
            <a class="nav-link" aria-current="page" href="#" id="navbarDropdownMenuLink3" role="button" data-bs-toggle="dropdown" aria-expanded="false">Who we are <i class="fas fa-angle-down"></i></a>
            <ul class="dropdown-menu animate slideIn" aria-labelledby="navbarDropdownMenuLink3">
              <li><a class="dropdown-item" href="#">About us</a></li>
              <li><a class="dropdown-item" href="#">Blog</a></li>
            </ul>
          </li>
        </ul>
      <% end %>
        <div class="dropdown dropstart">
          <% if user_signed_in? %>
            <div class="flex-shrink-0">
              <a href="#" class="d-block link-warning text-decoration-none dropdown-toggle" id="dropdownUser" data-bs-toggle="dropdown" aria-expanded="false">
                <% if current_user.avatar.attached? %>
                  <%= image_tag current_user.avatar, class: "rounded-circle", width: "32", height: "32" %>
                <% else %>
                  <%= image_tag("default_profile.jpg", class: "rounded-circle", height: '32', width: '32') %>
                <% end %>
              </a>
              <ul class="dropdown-menu text-small shadow border-light animate slideIn" aria-labelledby="dropdownUser">
                <li><%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %></li>
                <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
              </ul>
            </div>
          <% else %>
            <button type="button" class="btn btn-header btn-md btn-dark me-2 rounded-pill dropdown-toggle" type="button" id="dropdownLoginButton" data-bs-toggle="dropdown" aria-expanded="false"> Login</button>
            <ul class="dropdown-menu dropdown-menu-dark drop-login animate slideIn" aria-labelledby="dropdownLoginButton">
              <li><%= link_to "as Admin", new_admin_session_path, class:"dropdown-item"%></li>
              <li><%= link_to "as Broker", new_broker_session_path, class:"dropdown-item"%></li>
              <li><%= link_to "as Buyer", new_buyer_session_path, class:"dropdown-item"%></li>
            </ul>
          <% end %>
      </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_hero.html.erb
<div class="row mt-5 align-items-center">
  <div class="col-6">
    <h1 class="hero-main">Investments for a <br> secured future</h1>
    <span class="hero-text">The only platform you need to increase your success. 
    <br> 
    Sign up and get your first stock for free.
    </span>
    <br>
    <div class="dropdown">
      <button type="button" class="btn btn-hero btn-lg mt-3 rounded-pill text-dark dropdown-toggle" type="button" id="dropdownSignUpButton" data-bs-toggle="dropdown" aria-expanded="false">
      Sign up
    </button>
    <ul class="dropdown-menu drop-sign animate slideIn" aria-labelledby="dropdownSignUpButton">
      <li><%= link_to "As Buyer", new_buyer_registration_path, class:"dropdown-item"%></li>
      <li><%= link_to "As Broker", new_broker_registration_path, class:"dropdown-item"%></li>
    </ul>
    </div>
  </div>
  <div class="col-6 p-2">
    <img src=<%= asset_path("hero-1.png") %> class="hero-img animate slideIn"/>
  </div>
    <img src=<%= asset_path("blob-hero.svg") %> class="blob-img"/>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>Stak | Stock Trading App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/033affd47f.js" crossorigin="anonymous"></script>
    <script src="https://cdn.lordicon.com/libs/frhvbuzj/lord-icon-2.0.2.js"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class=" d-flex h-100">
    <%= render 'layouts/header' %>
    <%= render partial: 'shared/flash' %>
    <% if user_signed_in? %>  
      <div class="container h-100">
        <%= yield %>
      </div>
    <% else %>
      <div class="container d-flex mx-auto h-100">
        <%= render 'layouts/hero' %>
      </div>
     <% end %>
    <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>Stak | Stock Trading App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/033affd47f.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="h-100">
    <div class="container h-100 pt-5">
      <%= render 'layouts/header' %>
      <%= render partial: 'shared/flash' %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>
  </body>
</html>